name: Build and GH-Page Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 19.x

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
          single-commit: false
